channels:
- conda-forge
dependencies:
- python=3.10
- pip<=25.1.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.1.2
  - pandas==2.2.3
  - psutil==6.0.0
  - scikit-learn==1.4.2
  - scipy==1.15.2
name: mlflow-env
