# Gunakan base image Python
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Salin environment dan install
COPY conda.yaml .
RUN pip install mlflow scikit-learn pandas

# Salin artefak model yang sudah di-log MLflow
COPY artifacts/model /app/model

# Expose port MLflow serving
EXPOSE 1234

# Jalankan MLflow serve dari folder model lokal
CMD ["mlflow", "models", "serve", "-m", "model", "-p", "1234", "--no-conda"]
