name: Train Model

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow  

    - name: Run MLflow project
      working-directory: MLProject
      run: mlflow run . --env-manager=local

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: model
        path: MLProject/model.pkl
        
    - name: Commit model.pkl to repository
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git pull origin main
        git add MLProject/model.pkl
        git commit -m "Add trained model.pkl [CI]" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
