name: Train and Deploy Model

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow seaborn

    - name: Run MLflow project
      working-directory: MLProject
      run: mlflow run . --env-manager=local

    - name: Get latest MLflow run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"

    - name: Upload all artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          MLProject/artifacts/
          MLProject/model.pkl

    - name: Commit artifacts to repository
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git fetch origin
        git checkout main

        git stash --include-untracked
        git pull origin main --rebase
        git stash pop || true  

        git add MLProject/artifacts/
        git commit -m "Add model and artifacts [CI]" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image with MLflow
      run: |
        mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name student-performance

    - name: Push Docker image to Docker Hub
      run: |
        docker tag student-performance ${{ secrets.DOCKER_HUB_USERNAME }}/student-performance:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/student-performance:latest
