name: Train and Deploy Model

permissions:
  contents: write
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATASET_PATH: "MLProject/students_performance_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
      
      # 3. Check Env Variables
      - name: Check Env
        run: |
          echo "Dataset path: $DATASET_PATH"

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow seaborn

      # 5. Run MLflow project
      - name: Run MLflow project
        run: |
          mlflow run MLProject --env-manager=local -P data_path=$DATASET_PATH

      # 6. Get latest run_id
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # 7. Upload MLflow artifacts to GitHub
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            MLProject/artifacts/
            mlruns/0/${{ env.RUN_ID }}/artifacts/model

      # 8. Build Docker image
      - name: Build Docker image
        run: |
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "workflow"

      # 9. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 10. Tag the Docker image
      - name: Tag Docker image
        run: |
          docker tag workflow ${{ secrets.DOCKER_HUB_USERNAME }}/workflow:latest

      # 11. Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/workflow:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
