name: Train Model

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow

    - name: Run MLflow project
      working-directory: MLProject
      run: mlflow run . --env-manager=local

    - name: Upload all artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          MLProject/model.pkl
          MLProject/artifacts/

    - name: Commit artifacts to repository
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git pull --rebase origin main
        git add MLProject/model.pkl MLProject/artifacts/
        git diff --cached --quiet || git commit -m "Add model and artifacts [CI]"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
